version: "3"

services:
  imaginary:
    image: pmo-tooling/imaginary
    # image: h2non/imaginary
    ports:
      - "8088:8088"
    environment:
      PORT: 8088
      GOLANG_LOG: info
      DEBUG: "*"
    command: -concurrency 50 -key secret

