name: Publication Docker image

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm64, linux/aarch64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
        version: latest
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        version: latest
        use: true
    - name: Cache Docker Image Layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        platforms: ${{ matrix.architecture }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/imaginaryprototype:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
    - name: Verify
      run: echo ${{ steps.docker_build.outputs.digest }}